
# do not use docker compose up. use the following sequence to deploy

# docker compose up db -d
# docker compose up adminder -d
# docker compose up app -d
version: '3'

networks:
  rfinder:
    name: rfinder

services:
  app:
   
    depends_on:
      - db
    networks:
      - rfinder
    build: .
    ports: 
      - "5000:8080"
    environment:
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=any_username
      - DATABASE_PASSWORD=any_password
      - DATABASE_NAME=any_database_name
      - JWTSECRET=long_string_like_kjrTowKXaSvY6QgWHloxeXXNWnF4ptzQex8COj4zqWnA0dogSR98oCX8/3u/wDj+
      - IOS_APP_ID=for_apple_login_your_ios_bundle_id
  db:
    image: "postgres"
    ports:
      - 5002:5432
    container_name: db_host_name
    networks:
       - rfinder
    environment:
      - POSTGRES_DB=vfinder
      - POSTGRES_USER=deploy
      - POSTGRES_PASSWORD=password


  adminer:
    image: adminer
    restart: always
    hostname: db_host_name
    container_name: vadminer
    networks:
       - rfinder
    ports:
      - 5001:8080

  